openapi: 3.0.3
info:
  title: Wallet API
  version: 1.0.0
  description: STD22037 - STD22077
servers:
  - url: https://hei.wallet.api.com
security:
  - oauth2: [ ]
paths:
components:
  parameters:
    PagePagination:
      name: page
      description: Pagination page, default is 1 if not specified
      in: query
      schema:
        type: integer
        default: 1
    PageSizePagination:
      name: pageSize
      description: Pagination page size, default is 50 if not specified
      in: query
      schema:
        type: integer
        default: 50
  schemas:
    TransactionBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBody'
        - properties:
            body:
              $ref: '#/components/schemas/Transaction'
    TransactionListBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBody'
        - properties:
            body:
              type: array
              items:
                $ref: '#/components/schemas/Transaction'
    TransactionType:
      type: string
      enum:
        - WITHDRAWAL
        - DEPOSIT
        - TRANSFER
    Transaction:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: '550e8400-e29b-41d4-a716-446655440000'
        ref:
          type: string
          example: '1201-244'
        type:
          $ref: '#/components/schemas/TransactionType'
        description:
          type: string
          example: 'Some description'
        amount:
          type: number
          format: float
          example: 2000.2
        transaction_datetime:
          type: string
          format: date-time
          example: '2021-01-01 02:01:01'
        destination_account:
          type: string
          format: uuid
          example: '550e8400-e29b-41d4-a716-446655440000'
        source_account:
          type: string
          format: uuid
          example: '550e8400-e29b-41d4-a716-446655440000'
    AccountBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBody'
        - properties:
            body:
              $ref: '#/components/schemas/Account'
    AccountListBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBody'
        - properties:
            body:
              type: array
              items:
                $ref: '#/components/schemas/Account'
    Account:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: '550e8400-e29b-41d4-a716-446655440000'
        name:
          type: string
          example: 'Account Name'
        type:
          $ref: '#/components/schemas/AccountType'
        balance:
          type: number
          format: float
          example: 2000.2
        number:
          type: string
          example: '101-0151'
        creation_date:
          type: string
          format: date
          example: '2023-01-01'
        comment:
          type: string
          example: some comments
        owner:
          type: string
          example: Rabe
        bank_name:
          type: string
          example: BMOI
        currency:
          $ref: '#/components/schemas/Acurrency'
    AccountType:
      type: string
      enum:
        - CHECKING
        - SAVING
        - BUSINESS
        - INVESTMENT
        - CERTIFICATE_OF_DEPOSIT
    AcurrencyBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBody'
        - properties:
            body:
              $ref: '#/components/schemas/Acurrency'
    AcurrencyListBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBody'
        - properties:
            body:
              type: array
              items:
                $ref: '#/components/schemas/Acurrency'
    Acurrency:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: '550e8400-e29b-41d4-a716-446655440000'
        name:
          type: string
          example: 'Ariary'
        code:
          type: string
          example: 'MGA'
        symbol:
          type: string
          example: 'Ar'
        exchange_rate:
          type: number
          format: float
          example: 0.0002
        updated_at:
          type: string
          format: date
          description: current_date if not specified
          example: '2023-01-01'
    ResponseBody:
      type: object
      properties:
        code:
          type: integer
          example: 200
        message:
          type: string
          example: OK
    PingBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBody'
      example:
        status:
          code: 200
          message: pong
        body: null
    BadRequestBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBody'
      example:
        status:
          code: 400
          message: BAD REQUEST
        body: null
    ForbiddenBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBody'
      example:
        status:
          code: 403
          message: FORBIDDEN
        body: null
    InternalServerError:
      allOf:
        - $ref: '#/components/schemas/ResponseBody'
      example:
        status:
          code: 500
          message: INTERNAL SERVER ERROR
        body: null
    responses:
      Transaction200:
        description: One Transaction
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionBody'
      TransactionList200:
        description: List of transactions
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionListBody'
      Account200:
        description: One Account
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountBody'
      AccountList200:
        description: List of accounts
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountListBody'
      Acurrency200:
        description: One acurrency
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcurrencyBody'
      AcurrencyList200:
        description: List of acurrencies
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcurrencyListBody'
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://hei.wallet.com
          scopes:
            anonyme: User not authentificated
            admin: User authentificated as admin
            user: User authentificated as simple user


